In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv(r"Desktop/academics/dsbda_practs/dataset_Facebook.csv", sep=";")

In [ ]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [ ]:
df.shape

(500, 19)

In [ ]:
df1=df[['Page total likes','Category','Post Month','Post Weekday']].loc[0:15]

In [ ]:
df1

    Page total likes  Category  Post Month  Post Weekday
0             139441         2          12             4
1             139441         2          12             3
2             139441         3          12             3
3             139441         2          12             2
4             139441         2          12             2
5             139441         2          12             1
6             139441         3          12             1
7             139441         3          12             7
8             139441         2          12             7
9             139441         3          12             6
10            139441         2          12             5
11            139441         2          12             5
12            139441         2          12             5
13            139441         2          12             5
14            138414         2          12             4
15            138414         2          12             3

In [ ]:
df2=df[['Page total likes','Category','Post Month','Post Weekday']].loc[16:30]

In [ ]:
df2

    Page total likes  Category  Post Month  Post Weekday
16            138414         3          12             3
17            138414         1          12             2
18            138414         3          12             2
19            138414         3          12             1
20            138414         2          12             1
21            138414         1          12             7
22            138414         1          12             7
23            138414         3          12             7
24            138414         2          12             6
25            138458         2          12             6
26            138458         2          12             5
27            138458         3          12             5
28            138895         2          12             5
29            138895         1          12             4
30            138895         2          12             4

In [ ]:
df3=df[['Page total likes','Category','Post Month','Post Weekday']].loc[31:50]

In [ ]:
df3

    Page total likes  Category  Post Month  Post Weekday
31            138895         2          12             3
32            138895         3          12             3
33            138895         3          12             2
34            138895         1          12             2
35            138895         2          12             1
36            138895         3          12             1
37            138895         1          12             7
38            138895         2          12             7
39            138895         1          12             7
40            138895         2          12             6
41            138895         1          12             6
42            138353         1          12             5
43            138353         1          12             5
44            138353         1          12             4
45            138353         1          12             4
46            138353         1          12             3
47            138353         1          12             3
48            138353         1          12             2
49            138353         1          12             2
50            138353         2          11             1

In [ ]:
merging = pd.concat([df1,df2,df3])

In [ ]:
merging

    Page total likes  Category  Post Month  Post Weekday
0             139441         2          12             4
1             139441         2          12             3
2             139441         3          12             3
3             139441         2          12             2
4             139441         2          12             2
5             139441         2          12             1
6             139441         3          12             1
7             139441         3          12             7
8             139441         2          12             7
9             139441         3          12             6
10            139441         2          12             5
11            139441         2          12             5
12            139441         2          12             5
13            139441         2          12             5
14            138414         2          12             4
15            138414         2          12             3
31            138895         2          12             3
32            138895         3          12             3
33            138895         3          12             2
34            138895         1          12             2
35            138895         2          12             1
36            138895         3          12             1
37            138895         1          12             7
38            138895         2          12             7
39            138895         1          12             7
40            138895         2          12             6
41            138895         1          12             6
42            138353         1          12             5
43            138353         1          12             5
44            138353         1          12             4
45            138353         1          12             4
46            138353         1          12             3
47            138353         1          12             3
48            138353         1          12             2
49            138353         1          12             2
50            138353         2          11             1
31            138895         2          12             3
32            138895         3          12             3
33            138895         3          12             2
34            138895         1          12             2
35            138895         2          12             1
36            138895         3          12             1
37            138895         1          12             7
38            138895         2          12             7
39            138895         1          12             7
40            138895         2          12             6
41            138895         1          12             6
42            138353         1          12             5
43            138353         1          12             5
44            138353         1          12             4
45            138353         1          12             4
46            138353         1          12             3
47            138353         1          12             3
48            138353         1          12             2
49            138353         1          12             2
50            138353         2          11             1

In [ ]:
sort_values=df.sort_values('Page total likes', ascending=False)

In [ ]:
sort_values

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
36,138895,Photo,3,12,1,3,0.0,2690,4628,252,168,226,3052,1727,199,0,96.0,17.0,113
30,138895,Photo,2,12,4,2,0.0,4940,9390,385,306,501,5860,2930,273,33,107.0,22.0,162
31,138895,Photo,2,12,3,10,0.0,1683,2929,192,171,221,1585,858,131,1,27.0,11.0,39
33,138895,Photo,3,12,2,9,0.0,3002,5318,268,185,247,3039,1676,194,4,98.0,23.0,125
34,138895,Photo,1,12,2,3,0.0,3766,7149,298,260,431,5782,2938,244,2,56.0,17.0,75
35,138895,Photo,2,12,1,11,0.0,4512,7808,423,284,431,5183,2954,316,6,172.0,21.0,199
39,138895,Photo,1,12,7,3,0.0,3290,6085,306,284,402,4986,2584,247,1,44.0,14.0,59
37,138895,Photo,1,12,7,10,1.0,19800,28663,479,424,805,5187,2752,248,16,76.0,8.0,100
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
32,138895,Photo,3,12,3,3,0.0,5280,9578,368,237,345,4480,2422,268,2,155.0,47.0,204
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0,0,0,1,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79,130,66,1572,325,152,249,325,161,113,...,79,105,128,185,125,53,53,93,91,91
share,17,29,14,147,49,33,27,14,31,26,...,30,46,9,55,41,26,22,18,38,28
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [ ]:
transposing=df.transpose()

In [ ]:
transposing

In [ ]:
#shaping

In [ ]:
shaping=df.shape

In [ ]:
shaping

(500, 19)

In [ ]:
#ereshaping

In [ ]:
pivot_table = pd.pivot_table(df, index=['Type','Category'],values='comment')

In [ ]:
print(pivot_table)

                   comment
Type   Category
Link   1          2.900000
       2          2.000000
       3          2.000000
Photo  1          5.897297
       2         11.692308
       3          6.913333
Status 1          4.333333
       2          9.921053
       3          2.750000
Video  1         12.285714

In [ ]:
reshaping_arr = np.array([1,2,3,4,5,6])
reshaping_arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])